#!/bin/bash -l
#SBATCH --job-name=GWAS_plots
#SBATCH --output=GWAS_plots.%j.out
#SBATCH --error=GWAS_plots.%j.err
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=8G
#SBATCH -p batch

# Load conda
source /data/leuven/385/vsc38531/miniconda3/etc/profile.d/conda.sh

# Activate pre-created environment
conda activate r_gwas

# Fail on error
set -euo pipefail

# Run script
Rscript GWAS_plots.R
